config/production.yml
config/test.yml
templates/dask/dask-service.template.yml
templates/datalab/datalab-api-deployment.template.yml
templates/datalab/datalab-app-deployment.template.yml
templates/datalab/docs-deployment.template.yml
templates/minio/minio-connect-deployment.template.yml
templates/minio/minio-deployment.template.yml
templates/spark/spark-ui-proxy-deployment.yml
templates/thredds/thredds-service.template.yml

Correct templates to replace domain into ingress rules

Template ingress

---

config/ceh-production.yml
config/production.yml
config/test.yml
templates/datalab/auth0-configmap.template.yml
templates/datalab/datalab-api-deployment.template.yml
templates/datalab/datalab-auth-deployment.template.yml
templates/datalab/infrastructure-api-deployment.template.yml

Adding config for CEH deployment, also included deployment to test yesterday

CEH Deployment

---

config/production.yml
config/test.yml
templates/datalab/datalab-auth-deployment.template.yml
templates/management/backup/backup-etcd-cronjob.yml
templates/management/backup/backup-etcd-persistent-volume.yml

Backup etcd

---

config/test.yml

Deployed new version for demo this morning

feat: deploy 0.26.0-71-g0c79c97 [test]

---

config/test.yml
templates/busybox.yml
templates/datalab/datalab-api-deployment.template.yml
templates/datalab/datalab-app-deployment.template.yml
templates/datalab/datalab-auth-deployment.template.yml
templates/datalab/datalab-ingress.template.yml
templates/datalab/infrastructure-api-deployment.template.yml

Update API audience
Update Ingress routing to put api on same domain as app

feat: deploy 0.26.0-79-g78ea7c8 [test]

---

README.md
config/test.yml
templates/management/vault-unseal/vault-unseal-cronjob.yml

Have deployed this now on the test cluster, seems to be working fine.

feat: adding vault unseal manifest

---

templates/datalab/datalab-auth-deployment.template.yml

Update permissions section of auth service deployment config to match that used in the auth service when running locally.

feat(auth deployment): update permissions section

---

templates/datalab/compute-submission-role.yml
templates/datalab/infrastructure-authorisation.template.yml

Superseeds #88 after testing the Dask/Spark work.

Fix roles for spark deployment

---

templates/datalab/infrastructure-authorisation.template.yml

Added resource "deployments/scale" to ClusterRole infrastructure-management-role so that infrastructure-service-account can restart notebooks.
File also auto-formatted.

feat: add deployments/scale resource

---

templates/datalab/datalab-api-deployment.template.yml
templates/datalab/datalab-app-deployment.template.yml
templates/datalab/infrastructure-api-deployment.template.yml
templates/datalab/storage-configmap.template.yml

Links with https://github.com/NERC-CEH/datalab/pull/599

NERCDL-679 config map for storage

---

config/test.yml
templates/datalab/datalab-app-deployment.template.yml
templates/datalab/image-configmap.template.yml
templates/datalab/infrastructure-api-deployment.template.yml

Update to latest version and add the image config map.

feat: update version to deploy and add image config map

---

config/mongo/test/userRoles.json

Add catalog roles to test instance users.

NERCDL-786 add catalog permissions

---

config/test.yml
templates/datalab/datalab-auth-deployment.template.yml

Ups the DockerHub version and changes the config map for permissions.yml

release NERCDL-664 and 786

---

README.md
helm/datalab/Chart.yaml
helm/datalab/templates/configmaps/image-configmap.template.yml

Release NERCDL-812, Remove duplicated code in stackTypes.js, since we are now using ConfigMaps.

feat: release NERCDL-812

---

helm/datalab/Chart.yaml
helm/datalab/templates/configmaps/oidc-configmap.template.yml

Release NERCDL-867, including update to oidc-configmap.template.yaml.

Release NERCDL-867

---

.github/workflows/pr.yaml
.github/workflows/push.yaml
README.md
datalab-k8s-manifests.code-workspace
helm/datalab/Chart.yaml
helm/datalab/templates/configmaps/oidc-configmap.template.yml
package.json
schema/catalogue-configmap.json
schema/image-configmap.json
schema/oidc-configmap.json
schema/storage-configmap.json
src/configMapJson.spec.js

This PR is probably best reviewed and merged after https://github.com/NERC-CEH/datalab-k8s-manifests/pull/119.
Validates configmaps and tests with github build actions.
In writing the tests, spotted a minor bug in oidc-configmap.template.yaml ("600" should be 600, i.e. a number not a string).
I'll create a PR to fix this in the datalabs repo.

NERCDL-863 validate configmaps

---

helm/datalab/Chart.yaml
helm/datalab/templates/configmaps/oidc-configmap.template.yml

Spotted an extra helm variable that could be used in the oidc config.
Probably best to review/merge this after "Release NERCDL-867".

Fix  use helm variable in oidc config

---

helm/datalab/templates/datalab-auth-deployment.template.yml

Accompanies https://github.com/NERC-CEH/datalab/pull/662, handles new permissions for data manager.

NERCDL-909 create asset repo > add metadata page

---

helm/datalab/Chart.yaml
helm/datalab/templates/infrastructure-api-deployment.template.yml

And fix bug with infrastructure-api-deployment template.

feat: release NERCDL-910 Add Metadata form

---

README.md
helm/datalab/Chart.yaml
helm/datalab/values.yaml

Have tested this configuration which worked well! Just adding a flag so it can be turned on & off and updated README, if this all looks good then would be good to raise a PR to master so we can make sure it's deployed in test (recently it's been removed as we're deploying the master branch).

feat: add enabled flag so catalogue can be turned on/off

---

helm/datalab/Chart.yaml
helm/datalab/templates/configmaps/clusters-configmap.template.yml
schema/clusters-configmap.json

Release code to create k8s Dask cluster, with fuller configmap definition.

feat: release NERCDL-964

---

helm/datalab/Chart.yaml
helm/datalab/templates/infrastructure-authorisation.template.yml

Releases fix - volume mount should be optional when creating clusters

Release fix for NERCDL-958

---

helm/datalab/Chart.yaml
helm/datalab/templates/configmaps/catalogue-asset-repo-configmap.template.yml
helm/datalab/values.yaml
schema/catalogue-asset-repo-configmap.json

For the moment I've just set the catalogueUrl to https://www.google.co.uk/, but it's easy to change.

NERCDL-916,858,1042 - release and update catalogue config

---

helm/datalab/templates/configmaps/image-configmap.template.yml

Use minio values in image configmap

---

helm/datalab/Chart.yaml
helm/datalab/templates/configmaps/clusters-configmap.template.yml
helm/datalab/templates/configmaps/image-configmap.template.yml
schema/clusters-configmap.json

Updated config maps to include spark cluster and latest spark image.
Bumped datalab helm version to include updates from the main repo.

NERCDL-1089: Spark changes

---

helm/datalab/templates/configmaps/notifications-configmap.template.yml
helm/datalab/templates/infrastructure-api-deployment.template.yml

Added the config map for email notifications - currently this is just a dummy one until we sort out how to use an email account.

Nercdl 1140 email notifications

---

helm/datalab/Chart.yaml
helm/datalab/templates/configmaps/image-configmap.template.yml
schema/image-configmap.json

Added Panel and Voila images to the images config map.
Also updated the image version - this includes both Panel/Voila changes, as well as those to add assets to notebooks (1135).

NERCDL-1058: Panel and Voila config

---

.github/workflows/pr.yaml
.github/workflows/push.yaml

updated actions to use node 16

Nercdl 1143 update node

---

helm/datalab/templates/configmaps/feature-flags.template.yml
helm/datalab/templates/datalab-app-deployment.template.yml

Added the config maps needed for feature flags in the web app

added a new config map for feature flags in the web app

---

helm/datalab/Chart.yaml

Updated app version for asset updates

NERCDL-1008: Updated app version for asset updates

---

helm/datalab/templates/datalab-api-deployment.template.yml
helm/datalab/templates/datalab-auth-deployment.template.yml
helm/datalab/templates/infrastructure-api-deployment.template.yml

Updated the version to have the new mongo status checks in, I've also increased the time between liveness checks as it's very rapid when mongo goes down and restarts too often to give mongo chance to stabilise when coming back up.

Mongo status updates

---

helm/datalab/values.yaml

This catalogue version includes several new features needed for the DUKEMS project

Update catalogue tag

---

helm/datalab/templates/configmaps/oidc-configmap.template.yml

PR to updtae oidc confgmap to use custom domain

chore: updating oidc configmap to use custom domain
